# Generated by Django 5.0.3 on 2024-04-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_ID', models.IntegerField(blank=True, null=True)),
                ('Cust_Name', models.CharField(default='', max_length=150)),
                ('Cust_Adress', models.CharField(default='', max_length=150)),
                ('Cust_Phone', models.IntegerField(blank=True, null=True)),
                ('Cust_Email', models.EmailField(default='', max_length=150)),
                ('Cust_Password', models.CharField(default='', max_length=150)),
                ('Cust_Status', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacture_ID', models.IntegerField(blank=True, null=True)),
                ('Manufacture_Name', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'Manufactures',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_ID', models.IntegerField(blank=True, null=True)),
                ('Type_Name', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'Types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(blank=True, null=True)),
                ('Role', models.CharField(default='', max_length=150)),
                ('User_Name', models.CharField(default='', max_length=150)),
                ('Password', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.IntegerField(blank=True, null=True)),
                ('Product_Img', models.ImageField(blank=True, null=True, upload_to='image_product/')),
                ('Product_Name', models.CharField(default='', max_length=150)),
                ('Configuration', models.CharField(default='', max_length=150)),
                ('Description', models.TextField(default='')),
                ('Quantity_In_Store', models.IntegerField(blank=True, null=True)),
                ('Unit_Price', models.IntegerField(default='', max_length=150)),
                ('Warranty', models.CharField(default='', max_length=150)),
                ('Other', models.CharField(default='', max_length=150)),
                ('Manufacture_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.manufacture')),
                ('Type_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.type')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.product')),
            ],
            options={
                'db_table': 'Shopping_Cart',
            },
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.IntegerField(blank=True, null=True)),
                ('Unit_Price', models.IntegerField(blank=True, null=True)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.product')),
                ('Quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.shopping_cart')),
            ],
            options={
                'db_table': 'Order_Details',
            },
        ),
    ]
