# Generated by Django 5.0.3 on 2024-04-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_ID', models.CharField(default='', max_length=150)),
                ('Cust_Name', models.CharField(default='', max_length=150)),
                ('Cust_Adress', models.CharField(default='', max_length=150)),
                ('Cust_Phone', models.CharField(default='', max_length=150)),
                ('Cust_Email', models.CharField(default='', max_length=150)),
                ('Cust_Password', models.CharField(default='', max_length=150)),
                ('Cust_Status', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacture', models.CharField(default='', max_length=150)),
                ('Product_ID', models.CharField(default='', max_length=150)),
                ('Product_Img', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('Product_Name', models.CharField(default='', max_length=150)),
                ('Configuration', models.CharField(default='', max_length=150)),
                ('Description', models.CharField(default='', max_length=500)),
                ('Quantyti_In_Store', models.CharField(default='', max_length=150)),
                ('Unit_Price', models.CharField(default='', max_length=150)),
                ('Warranty', models.CharField(default='', max_length=150)),
                ('Other', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_ID', models.CharField(default='', max_length=150)),
                ('Type_Name', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'Types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(default='', max_length=150)),
                ('Role', models.CharField(default='', max_length=150)),
                ('User_Name', models.CharField(default='', max_length=150)),
                ('PassWord', models.CharField(default='', max_length=150)),
                ('Status', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(default='', max_length=150)),
                ('Unit_Price', models.CharField(default='', max_length=150)),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.product')),
            ],
            options={
                'db_table': 'Order_Details',
            },
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seasion_ID', models.CharField(default='', max_length=150)),
                ('Quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.order_detail')),
            ],
            options={
                'db_table': 'Shopping_Cart',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Type_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest_app.type'),
        ),
    ]
